version: '3'
services:
  mininet:
    build:
      context: .
    image: diamino/mininet
    tty: true
    network_mode: "bridge"
    privileged: true
    environment:
     - DISPLAY=host.docker.internal:0
    volumes:
     - /lib/modules:/lib/modules
     - ${MININET_WORK:-.}:/opt/work
